"""add suggested_accounts

Revision ID: 26abd0702ed0
Revises: a9aec0537fcc
Create Date: 2026-06-06 15:39:15.188074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '26abd0702ed0'
down_revision: Union[str, None] = 'a9aec0537fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('suggested_accounts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'suggested_accounts')
    # ### end Alembic commands ###

