"""add icon and target_customer to packages

Revision ID: 4ec2a1c6449a
Revises: 010_add_suggested_accounts
Create Date: 2026-06-21 00:52:35.395764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ec2a1c6449a'
down_revision: Union[str, None] = '010_add_suggested_accounts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('packages', sa.Column('target_customer', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'target_customer')
    op.drop_column('packages', 'icon')
    # ### end Alembic commands ###
